services:
  demo:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./data:/app/data
    networks:
      - traefik_network
      - internal_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.clo36-datasets-demo.rule=Host(`datasets.services.dsi.wisc.edu`)"
      - "traefik.http.routers.clo36-datasets-demo.entrypoints=websecure"
      - "traefik.http.routers.clo36-datasets-demo.tls=true"
      - "traefik.http.routers.clo36-datasets-demo.tls.certresolver=myresolver"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - internal_network
    ports:  # For remote development (TODO: remove when stable)
      - "$POSTGRES_PORT:5432"
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 15s
    restart: always
    shm_size: 4gb
    command: >
      postgres
      -c shared_buffers=2GB
      -c work_mem=256MB
      -c effective_cache_size=4GB
      -c wal_buffers=256MB
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.1
      -c max_connections=50
networks:
  traefik_network:
    external: true
  internal_network:
    driver: bridge