services:
  demo:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.datasets.rule=Host(`datasets.services.dsi.wisc.edu`)"
      - "traefik.http.routers.datasets.entrypoints=websecure"
      - "traefik.http.routers.datasets.tls=true"
      - "traefik.http.routers.datasets.tls.certresolver=myresolver"
    restart: unless-stopped

networks:
  traefik_network:
    external: true
