[project]
name = "pelican-data-loader"
version = "0.1.0"
description = "Pelican Platform backed data loader"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.13",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
