services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-main.rule=Host(`minio.services.dsi.wisc.edu`)"
      - "traefik.http.routers.minio-main.entrypoints=websecure"
      - "traefik.http.routers.minio-main.tls=true"
      - "traefik.http.routers.minio-main.tls.certresolver=myresolver"
    ports:
      - "9001:9001" # MinIO Console local access
    networks:
      - traefik_network

volumes:
  minio-data:

networks:
  traefik_network:
    external: true
